### ISSUE TITLE
LuxMedError: In order to use this app, please update it to the newest version available in the store (code 301)

### ISSUE THREAD

**Issue by kubawolanin** [przemal/luxmed#1]
Hi @przemal 
Thanks for your work on this.

Unfortunately this lib no longer works.
Steps to reproduce:

1. `pip install -e git+https://github.com/przemal/luxmed#egg=luxmed`
2. Paste the example code from README.md
3. Run the script:

```
$ python main.py
Traceback (most recent call last):
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\transport.py", line 54, in _request
    response.raise_for_status()
  File "C:\Users\kubaw\.platformio\penv\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://portalpacjenta.luxmed.pl/PatientPortalMobileAPI/api/token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projects\ha-luxmed\main.py", line 6, in <module>
    print(luxmed.user())
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\luxmed.py", line 71, in user
    return self._transport.get(USER_URL)
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\transport.py", line 97, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\transport.py", line 90, in request
    self.authenticate()
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\transport.py", line 71, in authenticate
    token = self._request('POST', TOKEN_URL, data={
  File "c:\users\kubaw\.platformio\penv\src\luxmed\luxmed\transport.py", line 56, in _request
    raise LuxMedError.from_response(response) from error
luxmed.errors.LuxMedError: In order to use this app, please update it to the newest version available in the store (code 301)
(penv)
```

**Comment by dzienisz** [comment]
can you check again as this was merged https://github.com/przemal/luxmed/commit/46eabb55a837a9bcb327f605816ca47338a2576c
